"use client";

import { FormattedMessage } from "react-intl";

const PrivacyPolicyPage = () => {
  return (
    <div className="p-6 max-w-3xl mx-auto">
      <h1 className="text-2xl font-bold mb-4">
        <FormattedMessage id="privacy_policy.title" defaultMessage="Privacy Policy" />
      </h1>

      <p className="mb-2">
        <strong><FormattedMessage id="privacy_policy.last_updated_label" defaultMessage="Last Updated:" /></strong>{" "}
        <FormattedMessage id="privacy_policy.last_updated" defaultMessage="August 7, 2025" />
      </p>

      <p className="mb-4">
        <FormattedMessage
          id="privacy_policy.data_controller"
          defaultMessage="TradingBacktesting (legal name and tax ID if applicable) is responsible for processing users' personal data."
        />
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.data_we_collect_title" defaultMessage="Data We Collect" />
      </h2>
      <ul className="list-disc pl-6 mb-4">
        <li><FormattedMessage id="privacy_policy.data_we_collect.1" defaultMessage="Registration data (name, email, etc.)" /></li>
        <li><FormattedMessage id="privacy_policy.data_we_collect.2" defaultMessage="Usage data (IP address, browser type, visited pages)" /></li>
        <li><FormattedMessage id="privacy_policy.data_we_collect.3" defaultMessage="Strategy and performance data from backtesting" /></li>
        <li><FormattedMessage id="privacy_policy.data_we_collect.4" defaultMessage="Trade history and metrics pulled from MetaTrader 4 and 5 (with prior user authorization)" /></li>
      </ul>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.purpose_of_processing_title" defaultMessage="Purpose of Processing" />
      </h2>
      <ul className="list-disc pl-6 mb-4">
        <li><FormattedMessage id="privacy_policy.purpose.1" defaultMessage="Deliver and improve our services" /></li>
        <li><FormattedMessage id="privacy_policy.purpose.2" defaultMessage="Provide backtesting analysis based on actual trading data" /></li>
        <li><FormattedMessage id="privacy_policy.purpose.3" defaultMessage="Enhance user experience" /></li>
        <li><FormattedMessage id="privacy_policy.purpose.4" defaultMessage="Send operational, support, or promotional communications (with prior consent)" /></li>
      </ul>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.external_integrations_title" defaultMessage="External Integrations" />
      </h2>
      <p className="mb-2"><FormattedMessage id="privacy_policy.external_integrations.platforms" defaultMessage="Platforms: MetaTrader 4, MetaTrader 5" /></p>
      <ul className="list-disc pl-6 mb-4">
        <li><FormattedMessage id="privacy_policy.external_integrations.1" defaultMessage="Access limited strictly to historical trading data generated by the user" /></li>
        <li><FormattedMessage id="privacy_policy.external_integrations.2" defaultMessage="We do not execute trades or interfere with live accounts" /></li>
        <li><FormattedMessage id="privacy_policy.external_integrations.3" defaultMessage="We do not manage capital or provide portfolio management services" /></li>
        <li><FormattedMessage id="privacy_policy.external_integrations.4" defaultMessage="Access is read-only and limited to analytical purposes" /></li>
      </ul>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.legal_grounds_title" defaultMessage="Legal Grounds" />
      </h2>
      <ul className="list-disc pl-6 mb-4">
        <li><FormattedMessage id="privacy_policy.legal_grounds.1" defaultMessage="User consent" /></li>
        <li><FormattedMessage id="privacy_policy.legal_grounds.2" defaultMessage="Contractual necessity" /></li>
        <li><FormattedMessage id="privacy_policy.legal_grounds.3" defaultMessage="Legitimate interests" /></li>
      </ul>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.data_retention_title" defaultMessage="Data Retention" />
      </h2>
      <p className="mb-4">
        <FormattedMessage
          id="privacy_policy.data_retention"
          defaultMessage="We retain user data as long as the account is active or until the user requests deletion."
        />
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.user_rights_title" defaultMessage="User Rights" />
      </h2>
      <ul className="list-disc pl-6 mb-4">
        <li><FormattedMessage id="privacy_policy.user_rights.1" defaultMessage="Access" /></li>
        <li><FormattedMessage id="privacy_policy.user_rights.2" defaultMessage="Rectification" /></li>
        <li><FormattedMessage id="privacy_policy.user_rights.3" defaultMessage="Deletion" /></li>
        <li><FormattedMessage id="privacy_policy.user_rights.4" defaultMessage="Objection" /></li>
        <li><FormattedMessage id="privacy_policy.user_rights.5" defaultMessage="Data portability" /></li>
        <li><FormattedMessage id="privacy_policy.user_rights.6" defaultMessage="Restriction of processing" /></li>
      </ul>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.contact_title" defaultMessage="Contact" />
      </h2>
      <p className="mb-4">
        <FormattedMessage
          id="privacy_policy.contact"
          defaultMessage="To exercise your rights, contact us at: email@tradingbacktesting.com"
        />
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.cookies_title" defaultMessage="Cookies" />
      </h2>
      <p className="mb-4">
        <FormattedMessage
          id="privacy_policy.cookies"
          defaultMessage="We use technical, analytical, and personalization cookies. You can manage them through your browser or via our cookie consent banner."
        />
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.international_data_transfers_title" defaultMessage="International Data Transfers" />
      </h2>
      <p className="mb-4">
        <FormattedMessage
          id="privacy_policy.international_data_transfers"
          defaultMessage="If we transfer your data outside your country, we will comply with all applicable regulations (e.g., EU Standard Contractual Clauses)."
        />
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        <FormattedMessage id="privacy_policy.security_title" defaultMessage="Security" />
      </h2>
      <p>
        <FormattedMessage
          id="privacy_policy.security"
          defaultMessage="We apply appropriate technical and organizational measures to ensure the security and confidentiality of personal data."
        />
      </p>
    </div>
  );
};

export default PrivacyPolicyPage;
